### ISSUE TITLE
尊敬的作者先生您好！

### ISSUE THREAD

**Issue by xixiaoBull** [zcyeee/EastMoney_Crawler#10]
我最近在准备一篇期末论文，您的爬虫方法解决了我的燃眉之急，万分感谢！
您的代码运行非常顺利，但是在MongoDB打开数据库的时候却有如下显示：
<img width="1024" alt="MongoDB报错" src="https://github.com/user-attachments/assets/1310bf27-5a16-462c-93e8-b82f39a33576">
我想问一下是不是我的MongoDB哪里的设置出现了问题
还有一个问题就是可不可以通过更改哪个参数精准爬取个股某一个时间范围的发帖，而不是某一个页码范围？
希望能够得到您的回复，再次感谢！

**Comment by zcyeee** [comment]
你好！

关于第一个问题我不太确定（因为我用的是navicat😯，而且没有碰到过这样的报错），~~但是我猜测是不是你的文件夹层级弄错了呀，因为我这里对应的connection貌似只有一个（如下图）~~。
第二个问题是因为我又懒又菜🤓，只写了按照页码范围爬取的方法，所以目前没法通过修改某些参数直接按时间爬取发帖（不过评论还是可以按照时间爬取的hhhh）。
<img width="260" alt="截屏2024-11-27 12 20 39" src="https://github.com/user-attachments/assets/6a619b29-aa28-4870-8895-a8a76f2f426b">
还有什么问题如果你不介意的话也可以加 vx： 交流，可能更方便些hhhh
最后也祝你期末论文顺利！！

二编（解决办法存档）：
报错情况：
![WechatIMG18](https://github.com/user-attachments/assets/5004ec5a-b712-4e8c-852c-9c02605ed9da)
解决办法：[MongoDB Compass 报错 Invalid UTF-8 string in BSON document](https://blog.csdn.net/qq_22334245/article/details/136176959)
