### ISSUE TITLE
"post_url" error

### ISSUE THREAD

**Issue by jhzhou002** [zcyeee/EastMoney_Crawler#3]
![image](https://github.com/zcyeee/EastMoney_Crawler/assets/117413703/a2fbb40c-faaf-4b75-a846-8182db2eb350)
这种问题是什么原因呢

**Comment by zcyeee** [comment]
可以检查下是否在爬取comment之前爬取了对应股票的post信息呢

**Comment by jhzhou002** [comment]
post信息没结束我中断了，直接爬取comment报的错，是中断的原因吗

**Comment by zcyeee** [comment]
按理来说不会有影响，要不检查一下你想要爬取的comment的日期范围是否是已经爬取了的post信息的日期范围的子集

**Comment by zzy-st** [comment]
> post信息没结束我中断了，直接爬取comment报的错，是中断的原因吗

你好，请问这个问题你解决了吗，我也是相同的报错

**Comment by zcyeee** [comment]
在爬取完发帖信息后，运行爬取评论信息的代码如下：
```thread1 = threading.Thread(target=comment_thread_date, args=('000333', '2020-01-01', '2023-01-21'))```
此时代码文件初始的时间范围为`2020-01-01`和`2023-01-21`，而最开始爬取的那几页发帖信息的时间范围并没有包括这个时间段，所以会报错。
**即爬取评论信息时需确保设置的时间范围为已爬取的发帖信息范围的子集。**
