### ISSUE TITLE
大佬能问一下，无法获取listitem的div.update.pub_time怎么办啊

### ISSUE THREAD

**Issue by cstk2715** [zcyeee/EastMoney_Crawler#5]
![image](https://github.com/user-attachments/assets/ca4ba9b9-8398-4af2-9084-1a871a8c2cc5)

**Comment by cstk2715** [comment]
是因为网页为完全加载还是其他什么原因啊？之前尝试着爬都没出这个问题

**Comment by cstk2715** [comment]
已解决，原因是当时运行的时候listitems中的第一个listitem是话题类型的（guba.eastmoney.com/topic）,原先程序中检测的是   
 **if guba.eastmoney.com in url** ，但topic中的是记录发布时间的属性是‘update’，因此会导致找不到pub_time.

**Comment by cstk2715** [comment]
知道问题了，假如listitems中有一个listitem的url包含gubatopic.eastmoney.com，那么这个listitem的属性就与其他的不同，这就没有pub_time这个属性，取而代之的是update，这就会造成无法爬取。因此要么直接跳过那一页，或者检测有无gubatopic.eastmoney.com并跳过

**Comment by zcyeee** [comment]
非常感谢你的issue🤓，并且一针见血地指出了问题所在，我也会抽空修复这个小bug。最后祝您生活愉快！🎉

**Comment by zcyeee** [comment]
已顺利修复😌
