### ISSUE TITLE
time下的text或许不是完全由时间戳组成，可能附带汉字

### ISSUE THREAD

**Issue by cstk2715** [zcyeee/EastMoney_Crawler#6]
在 https://guba.eastmoney.com/news,832089,1460483446.html 这个帖子中，我发现假设time下的text会出现"修改于xxxx-xxxx-xxxx“这样的字段，这会导致爬虫一直出现异常，导致无法正常运行。或许需要对parsers的get_post_year方法做出修改，因为原方法是int(date_str[:4])，取前4个会是“修改于2”,无法int转换，不断抛出异常，重复。

**Comment by zcyeee** [comment]
收到，谢谢你的issue，已经通过正则表达式打上了布丁😃
