### ISSUE TITLE
作者大大

### ISSUE THREAD

**Issue by zj821220** [zcyeee/EastMoney_Crawler#9]
我在from crawler import PostCrawler报错说这个类没找到，cannot import name 'PostCrawler' from 'crawler' (D:\py\anaconda3\lib\site-packages\crawler\__init__.py)。请问PostCrawler和CommentCrawler是怎么定义的啊

**Comment by zcyeee** [comment]
PostCrawler 和 CommentCrawler 是我们定义在文件 `crawler` 中的两个类。导入报错的情况我之前也没有见过，也许可以试着改一下文件名字（？🥹

**Comment by zj821220** [comment]
> PostCrawler 和 CommentCrawler 是我们定义在文件 `crawler` 中的两个类。导入报错的情况我之前也没有见过，也许可以试着改一下文件名字（？🥹

我的crawler库里面只有这些东西from .base import * # noqafrom .request import * # noqafrom .response import * # noqa
_version__='0.0.2

**Comment by zcyeee** [comment]
不应该啊，`crawler` 文件里定义了 PostCrawler 和 CommentCrawler，我们是从项目文件里导入这两个类的。
<img width="583" alt="截屏2024-11-19 15 18 29" src="https://github.com/user-attachments/assets/8d90f603-e959-4a4e-999d-e02886639992">
